### ISSUE TITLE
[CFS] Query registry: SSL certificate problem

### ISSUE THREAD

**Issue by Samuele-Paglia** [mmul-it/training#29]
In the lab about [query registries](https://github.com/mmul-it/training/blob/master/Kubernetes-From-Scratch/Containers-Query-Registry.md) there is an SSL certificate problem when query the host https://www.mmul.it on port 5000.

**Comment by rascasoft** [comment]
Good catch! There was a problem on the automatic certificate renewal procedure, that now is fixed. Thanks!
